# Generated by Django 5.0.7 on 2024-07-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('title', models.CharField(max_length=120, verbose_name='Tittle')),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
