# Generated by Django 5.0.7 on 2024-07-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
