# Generated by Django 5.0.7 on 2024-07-22 01:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_story_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='angrys',
            field=models.ManyToManyField(blank=True, related_name='story_angry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='laughs',
            field=models.ManyToManyField(blank=True, related_name='story_laugh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='sads',
            field=models.ManyToManyField(blank=True, related_name='story_sad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='shocks',
            field=models.ManyToManyField(blank=True, related_name='story_shock', to=settings.AUTH_USER_MODEL),
        ),
    ]
