# Generated by Django 5.0.7 on 2024-07-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_story_angrys_story_laughs_story_sads_story_shocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
